- id: start_watering
  alias: 'Avvio irrigazione giardino'
  trigger:
   - platform: time
     at: '07:10:00'
  action:
    - service: switch.turn_on
      entity_id: switch.pompa
- id: stop_watering
  alias: 'Stop irrigazione giardino'
  trigger:
    - platform: time
      at: '07:15:00'
  action:
    - service: switch.turn_off
      entity_id: switch.pompa

