homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation_home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

recorder:
  purge_interval: 2
  purge_keep_days: 30
  db_url: sqlite:////home/homeassistant/home-assistant_v2.db

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

sun:

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key

# Text to speech
#tts:
#  - platform: google

climate:
  - platform: besmart
    name: Besmart Thermostat
    username: !secret besmart_user
    password: !secret besmart_pwd
    room: Soggiorno
    scan_interval: 120

binary_sensor:
  - platform: template
    sensors:
      heating:
        friendly_name: "Heating"
        value_template: "{{ is_state('climate.besmart_thermostat', 'on') }}"


logger:
  default: info
  logs:
    custom_components.climate.besmart: debug


history_graph:
  gr1:
    name: Temperature
    entities:
      - binary_sensor.heating
      - sensor.temperatura_giardino
      - sensor.temperatura_cucina
      - climate.besmart_thermostat
#.attributes.current_temperature
    hours_to_show: 1
    refresh: 60

mqtt:
  password: !secret mqtt_password
  
##########################
# Includes
##########################
sensor: !include sensors.yaml
switch: !include switches.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zwave:
  usb_path: /dev/zwave

