##########################
# Sensors
##########################

- platform: openweathermap
  api_key: !secret openweathermap_api_key
  forecast: 1
  monitored_conditions:
    - weather
    - temperature
    - rain

- platform: history_stats
  name: Thermostat ON today
  entity_id: climate.besmart_thermostat
  state: 'on'
  type: time
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24

- platform: mqtt
  state_topic: "/home/kitchen/temperature"
  name: "Temperatura Cucina"
  unit_of_measurement: '°C'

- platform: mqtt
  state_topic: "/home/kitchen/humidity"
  name: "Umidità Cucina"
  unit_of_measurement: '%'
  icon: mdi:water-percent

- platform: mqtt
  state_topic: "/home/garden/temperature"
  name: "Temperatura Giardino"
  unit_of_measurement: '°C'

- platform: mqtt
  state_topic: "/home/garden/humidity"
  name: "Umidità Giardino"
  unit_of_measurement: '%'
  icon: mdi:water-percent

- platform: template
  sensors:
      temperature_mode:
        friendly_name: "Temperature mode"
        value_template: "{{ state_attr('climate.besmart_thermostat', 'current_mode') }}"
      season_mode:
        friendly_name: "Season mode"
        value_template: "{{ state_attr('climate.besmart_thermostat', 'season_mode') }}"
      battery_state:
        friendly_name: "battery state"
        value_template: "{{ state_attr('climate.besmart_thermostat', 'battery_state') }}"
        icon_template: mdi:battery