##########################
# Sensors
##########################

- platform: openweathermap
  api_key: !secret openweathermap_api_key
  forecast: 1
  monitored_conditions:
    - weather
    - temperature
    - rain

- platform: history_stats
  name: Thermostat ON today
  entity_id: climate.besmart_thermostat
  state: 'on'
  type: time
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24

- platform: mqtt
  state_topic: "/home/kitchen/temperature"
  name: "Temperatura Cucina"
  unit_of_measurement: '°C'

- platform: mqtt
  state_topic: "/home/kitchen/humidity"
  name: "Umidità Cucina"
  unit_of_measurement: '%'
  icon: mdi:water-percent
