- platform: mqtt
  name: "Pompa"
  state_topic: "/home/garden/relay/0"
  command_topic: "/home/garden/relay/0/set"
  payload_on: 1
  payload_off: 0
  optimistic: false
  qos: 0
  retain: true

- name: FANCOIL1
  platform: mqtt
  state_topic: /home/espurna_1/relay/0
  command_topic: /home/espurna_1/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /home/espurna_1/status
  payload_available: 1
  payload_not_available: 0

